### PR TITLE
[Pull Request] - Ability to specifiy the line numbers that needs to be embedded.

### PR DESCRIPTION
**Pull request by sudar**
I have added the ability to specify the line numbers that needs to be embedded in addition to specifying the file name. It would be nice if you could accept the pull request.

Regards
Sudar

### CODE REVIEW

**Comment by robertkrimen** [comment]
I'll take a look at this, thanks

**Comment by sudar** [comment]
Thanks for considering my patch and incorporating it.

**Comment by nathggns** [comment]
Why hasn't this been merged yet? This is exactly what I need.

**Comment by robertkrimen** [comment]
This can be done through the slice parameter. See: https://gist-it.appspot.com/

**Pull request closed without merging**
